/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Arrays;


class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertEquals(3, classUnderTest.roll(3).length, "Roll method test failed");

        // TEST containsDuplicate()
        assertTrue(classUnderTest.containsDuplicates(new int[]{5, 5, 4, 2}), "Contain duplicate method failed");

        //TEST averageCalculator()
        assertEquals(5, classUnderTest.averageCalculator(new int[]{6,4,2,8}),  "Average calculator method failed");

        // TEST lowestAverage()
        int[][] weeklyMonthTemperatures = {
                {64, 66, 57, 71, 60, 57, 65},//62
                {59, 65, 63, 51, 72, 57, 70},//62
                {56, 60, 55, 59, 58, 60, 61},//58
                {59, 62, 52, 54, 60, 57, 55}//57
        };
        int[] arr = new int[]{59, 62, 52, 54, 60, 57, 55};
        assertEquals(Arrays.toString(arr), Arrays.toString(classUnderTest.lowestAverage(weeklyMonthTemperatures)));
    }
}
