/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Random;

public class Library {
    public static void main(String[] args) {
        System.out.println();
    }
    public int[] roll(int n) {
        int[] dice = {1, 2, 3, 4, 5, 6};
        int[] arr = new int[n];
        Random random = new Random();
        for (int i = 0; i < n; i++) {
            int randomIndex = random.nextInt(5);
            arr[i] = dice[randomIndex];
        }
        return arr;
    }

    public boolean containsDuplicates(int[] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array.length; j++) {
                if (i != j && array[i] == array[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public float averageCalculator(int[] array) {
        int sum = 0;
        for (int number : array) {
            sum = sum + number;
        }
        return (float) sum / array.length;
    }

    public int[] lowestAverage(int[][] array) {
        int sum = 0;
        float prevAvg;
        float avg = 0;
        int requiredIndex = 0;
        for (int i = 0; i < array.length; i++) {
            prevAvg = avg;
            sum = 0;
            for (int j = 0; j < array[i].length; j++) {
                sum = sum + array[i][j];
            }
            avg = (float) sum / array[i].length;
            if (avg < prevAvg) {
                requiredIndex = i;
            }

        }
        return array[requiredIndex];
    }
}

