/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {

        // 1- Restaurant toString method
        Restaurant res1 = new Restaurant("Burguer Maker",5);

        // 2- Review toString method
        Review rev1 = new Review("Nawal", "Good",3);
        Review rev2 = new Review("Sami", "Great",5);
        Review rev3 = new Review("Marwa", "bad",2);

        res1.addReview(rev1);
        res1.addReview(rev2);
        res1.addReview(rev3);
        System.out.println(res1.toString());

//        Restaurant res2 = new Restaurant("Burguer King",2);
//
//        Review rev4 = new Review("Nawal", "Good",3);
//        Review rev5 = new Review("Sami", "Great",2);
//        Review rev6 = new Review("Marwa", "bad",2);
//
//        res2.addReview(rev4);
//        res2.addReview(rev5);
//        res2.addReview(rev6);
//        System.out.println(res2.toString());
    }
}



