/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.checkerframework.checker.units.qual.A;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        Path path = Path.of("app/src/main/resources/gate.js");
//        Path path = Paths.get("gates.js");
        System.out.println(linter(path));
    }

    public static String linter(Path path){
        String errMsg ="";
        try {
            List<String> fileLines = Files.readAllLines(path);
            for (int i = 0; i < fileLines.size(); i++) {
                if(!fileLines.get(i).endsWith(";")){
                    if(!(fileLines.get(i).isBlank() || fileLines.get(i).endsWith("{") || fileLines.get(i).endsWith("}")|| fileLines.get(i).contains("if")||fileLines.get(i).contains("else"))) {
                        errMsg = errMsg + "Line "+ (i+1) +": Missing semicolon.\n";
                    }
                }
            }
        }
        catch (IOException exception){
            System.out.println("");
        }
        return  errMsg;
    }

}
