/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.checkerframework.checker.units.qual.A;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        Path path = Path.of("app/src/main/resources/gate.js");
        App newApp = new App();
        System.out.println(newApp.linter(path));
    }
    public String linter(Path path) {
        int counter = 0;
        StringBuilder errorLine = new StringBuilder();
        try {
            File myFile = new File(path.toUri());
            Scanner scanner = new Scanner(myFile);

            while (scanner.hasNextLine()) {
                counter++;
                String data = scanner.nextLine();
                if (!data.endsWith(";") && !data.endsWith("}") && !data.endsWith("{") && !data.contains("else") && !data.contains("if") && !data.isEmpty() || data.contains("return") && !data.endsWith(";")) {
                    errorLine.append("Line ").append(counter).append(" : Missing semicolon.\n");
                }
            }
            scanner.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        return errorLine.toString();
    }
}
