/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void restaurantTesting(){
        Restaurant BurgerMaker = new Restaurant("BurgerMaker",5);
        //toString method in Restaurant class is working properly.
        assertEquals(BurgerMaker.toString(),"Restaurant{Name='"+BurgerMaker.getName()+"',Rate of stars=0,Prices Category=$$$$$, reviewsList=[]}");
        assertNotNull(BurgerMaker,"ensure that Restaurant class work properly");
        assertEquals(5,BurgerMaker.getPriceCat());
    }
    @Test
    void reviewsTesting() {
        Restaurant BurgerMaker = new Restaurant("BurgerMaker",5);
        Review rev1=new Review("Ahmad", "Perfect",5);
        Review rev2=new Review("Sam", "bad",1);
        BurgerMaker.addReview(rev1);
        BurgerMaker.addReview(rev2);
        assertEquals(rev1.getAuthor(),"Ahmad");
        assertEquals(BurgerMaker.getStars(),3);
        //toString method in Review class is working properly.
        assertEquals(rev1.toString(),"Review{Author='Ahmad',Review body='Perfect',Rate of stars=5}");
        //toString method after update 5+1/2
        assertEquals(BurgerMaker.getStars(),3);
        //toString after addReview
        assertEquals(BurgerMaker.toString(),"Restaurant{Name='BurgerMaker',Rate of stars=3,Prices Category=$$$$$, reviewsList=[Review{Author='Ahmad',Review body='Perfect',Rate of stars=5}, Review{Author='Sam',Review body='bad',Rate of stars=1}]}");


        // For multiple Restaurant and Reviews
        Restaurant res2 = new Restaurant("res2", 3);
        Review rev3=new Review("Nahla", "worst",1);
        Review rev4=new Review("Hana", "bad",1);
        res2.addReview(rev3);
        res2.addReview(rev4);
        assertEquals(rev3.getAuthor(),"Nahla");
        assertEquals(res2.getStars(),1);

    }
    @Test
    void shopTesting(){
        Shop Zad = new Shop("Zad", "Good", 3);
        assertEquals(Zad.getName(),"Zad");
    }
}
